version: '3.8'

services:
  recognition-api:
    container_name: recognition-api

    build:
      context: ./recognition-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TESSDATA_PREFIX=/app/model/tesseract/
    volumes:
      - ./recognition-api:/app
    command: sh -c "uvicorn app:app --host 0.0.0.0 --port 8000"
    networks:
      - app-network
      
  upload-page:
    container_name: upload-page

    build:
      context: ./upload-page
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./upload-page:/app
    command: sh -c "npm install && node server.js"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge